### ISSUE TITLE
Renamed Printer does save as default between session

### ISSUE THREAD

**Issue by cadady** [zniezelski/Printerceptor#15]
Hello,

I have the script installed on a Windows Server 2012 R2 RD Session Host.  I installed the driver on the server for the printer model I am testing with.  I can see that the printer does get renamed as expected (%printername% - %user%).  However, if I set that printer to the user's default, it changes back to one of the local printer objects on the server the next session.  

I've removed the setting in GPO for "do not set the client's default printer as default", but I'm still seeing the issue.  

Appreciate any help in resolving this.  

Thank you.

**Comment by zniezelski** [comment]
Cadady,

It sounds like you want to set a redirected printer as the default printer that is not the default printer on the local client.

Please try this and let me know if it works for you or not.

1. Go into group policy and set "Do not set default client printer to be default printer in a session" back to "Not Configured"
2. In Printerceptor, create an advanced policy for each user with the conditions of the printer's driver you want to rename and the user of the printer. Set "rename" action and "Set printer with the following name as default" and enter the rename'ed name of the printer.

You are unable to just set the default printer and have it stick because windows stores the default printer in the registry with the name, port type and port name. The port name of the redirected printer changes per session and windows is unable to remember it.

I should probably add a "set default" action to avoid the need of putting the full rename'ed printer name in.

Hope this is helpful,

Zach

**Comment by cadady** [comment]
Zach,

I made the changes in GPO and I created an Advanced Policy for my test user (KENF) with the settings you recommended:

![image](https://user-images.githubusercontent.com/29925308/28041258-56e96744-658e-11e7-8935-55e8e0177d98.png)

I saved the policy and the settings in Printerceptor.  However, when I log on, I can see that the printer is being renamed correctly, but is not being set as default:

![image](https://user-images.githubusercontent.com/29925308/28041274-6b61ddb4-658e-11e7-867f-40e87b38d61c.png)

Am I still missing a setting?

Thank you

**Comment by zniezelski** [comment]
The pictures didn't come through. Can you send a different way. If you emailed them, maybe login to github and post on Web ui.

Thanks,

Zach



Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by cadady** [comment]
I updated the above comment with links to the pictures.

**Comment by zniezelski** [comment]
try this:

delete the policies I had you create and then make a new one just for setting the default printer.

check "Target users/clients instead of redirected printers. Set the User. Check "Set printer with following name as default" and enter the rename'ed name of the printer.

Zach

**Comment by zniezelski** [comment]
Cadady,

Did you have any success? Let me know if you need further assistance.

Thanks,

Zach

**Comment by cadady** [comment]
The customer ended up not needing the solution.  Thank you for your help.

Christian Dady  |  IT Services Engineer V

Loffler Companies, Inc.  |  1101 East 78th Street, Suite 200  |  Bloomington, MN 55420
Phone: +1 (952) 400-6968  |  Fax: +1 (952) 925-6801  |  www.loffler.com
