### ISSUE TITLE
Installation indicates English language not default

### ISSUE THREAD

**Issue by sbabcock61** [zniezelski/Printerceptor#22]
At the end of the installation, the installer indicates that English is not the default language.
Ours is set to : English (Canada) - US

Is there somtheing additional I need to do

Steve

**Comment by zniezelski** [comment]
Steve,

if a redirected printer does not look like "HP Officejet 8600 (redirected 5)" on English (Canada) - US then the regular expression will need to be changed.

Zach

**Comment by zniezelski** [comment]
Steve,

Did this work out for you? Let me know if I can help further.

Zach

**Comment by sbabcock61** [comment]
Yes - seems to work

I have another question ....

Powershell seems to be running when other user log in even though I
have enabled printerceptor for only 1 user - it then uses almost 50% of
a 4 core Xeon for about 15 - 30 seconds !!

Where are the Printerceptor parameters saved so that I can check to
config ?

Is PowerShell V1.0 ok to use ?
>>> zniezelski <notifications@github.com> 05/03/2019 6:47 AM >>>
Steve,
Did this work out for you? Let me know if I can help further.
Zach
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(
https://github.com/zniezelski/Printerceptor/issues/22#issuecomment-469650906)
, or mute the thread
(

**Comment by zniezelski** [comment]
Steve,

The script runs via the task scheduler every time a user logs in or reconnects to an RDP session. The script runs the powershell script under the system account because the built-in system account had full access to the redirected printers.

In the options you can play with the rounds and seconds to lower the time the script runs. It needs to run long enough for the printers to populate for the user so it can make the changes to the printers.

It might use a lot of CPU if there are a lot of printers. I think someone in the issues found that disabling windows defender helped reduce the CPU usage. 

The script requires at least Powershell 3.0

Zach

**Comment by sbabcock61** [comment]
This is running on Server 2008 R2 with Powershell 1.0 - I'll need to
upgrade it to 3.0

Just to confirm, the script runs even if the user is not listed ?


>>> zniezelski <notifications@github.com> 07/03/2019 9:40 AM >>>
Steve,
The script runs via the task scheduler every time a user logs in or
reconnects to an RDP session. The script runs the powershell script
under the system account because the built-in system account had full
access to the redirected printers.
In the options you can play with the rounds and seconds to lower the
time the script runs. It needs to run long enough for the printers to
populate for the user so it can make the changes to the printers.
It might use a lot of CPU if there are a lot of printers. I think
someone in the issues found that disabling windows defender helped
reduce the CPU usage.
The script requires at least Powershell 3.0
Zach
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(
https://github.com/zniezelski/Printerceptor/issues/22#issuecomment-470551000)
, or mute the thread
(

**Comment by zniezelski** [comment]
yes the script may be running if the user is not listed.
