### ISSUE TITLE
Polish language - one major problem

### ISSUE THREAD

**Issue by awalesa** [zniezelski/Printerceptor#3]
Hi

Thanks for such a great piece of script. We are testing the solution and we are geting one major problem. When the printer is created the name is changed but not into what we selected, and the created printer is unavailable for a user. 
1. the original printer name is: HP Universal Printing PCL 5
2. redirected printer name is: HP Universal Printing PCL 5 (przekierowana sesja: 2)
3. regex is: (\(przekierowana sesja: (\d+)\))
4. selected format is: %printername% - %username%
5. created printer name (in control panel) is: HP Universal Printing PCL 5 (przekierowana sesja: 2),4
6. printer from 5 is unavailable for user but when we run printer management there is correct printer: "HP Universal Printing PCL 5 - aleksander.walesa" and is available for user to print

Thanks for help,
Alex

**Comment by zniezelski** [comment]
Alex,

Thanks for reporting your issue.

What operating system are you running?

Are you only renaming the printer or is full access checked?

Thanks,

Zach

**Comment by awalesa** [comment]
Hi,

2012R2 and "Give full access to printer" enabled to allow tray assigment change. 

Thanks,
Alex

**Comment by zniezelski** [comment]
Make sure it has all of the Windows Updates and reboot the server.
Is it possible for me to remote into your machine and troubleshoot?

Thanks,

Zach

**Comment by awalesa** [comment]
I will do some tests to describe in more details what is going on - it looks that it works one time (first logon), and after next logon the problem arises. I will also prepare remote access for you - just give me your private email address.

**Comment by zniezelski** [comment]
zniezelski@lvtech.netmailto:zniezelski@lvtech.net RDP access would be best for troubleshooting.

Thanks,

Zach

**Comment by zniezelski** [comment]
Alex,

Are you still having trouble? I can take a look at it tonight if you can give me RDP access. zniezelski@lvtech.net

Thanks,

Zach

**Comment by awalesa** [comment]
Hi

Yes still fighting. I have send you access details directly. 

Thanks

**Comment by zniezelski** [comment]
Alex,

I remoted in and see the problem occurring.

I’m not exactly sure whats going on. I found some registry keys that don’t get renamed that are causing the printers to show in devices and printers.

I’ll work on it some more tomorrow.

Thanks,

Zach

From: Zachary Niezelski
Sent: Monday, August 1, 2016 9:01 AM
To: zniezelski/Printerceptor reply@reply.github.com; zniezelski/Printerceptor Printerceptor@noreply.github.com
Cc: Comment comment@noreply.github.com
Subject: RE: [zniezelski/Printerceptor] Polish language - one major problem (#3)

Make sure it has all of the Windows Updates and reboot the server.
Is it possible for me to remote into your machine and troubleshoot?

Thanks,

Zach

**Comment by awalesa** [comment]
Hi,

I don't know if it matters but we have GPO to use local/installed printer driver first before Easy Printing driver to speed up printing from RDP session. If I can help somehow just let me know. 

Thanks,

Alex

**Comment by zniezelski** [comment]
I think it has something to do with the universal print driver. I’m able to recreate the problem on my test setup. I tested with a different driver last night on your machine and couldn’t make the problem occur with a different driver. It might have something to do with how the driver interfaces with the devices and printers UI.
Zach

**Comment by zniezelski** [comment]
Alex,

I’ve been playing around a bit. Its kinda difficult to figure out exactly what is going on.

This is what I’m seeing so far:

·         Seems to only happen when logging into an existing session. I havn’t been able to make it happen when I “log off” and log back in.

·         I’m able to quickly make the problem happen by connecting to an existing session. If the redirected printers are populating and I connect in again quickly during that time it messes up.

I changed the amount of rounds in “options”  from 15 to 5 and the amount of delay from 5 seconds to 15 seconds and I havn’t been able to make the problem occur so far.

My guess is somewhere there are duplicate redirected printers being seen and it adds another number to it.

I’m thinking maybe if there is added delay to the script something in windows has more time to do something with redirected printers that keeps the problem from happening? If the script waits a while at each login before touching the printers it doesn’t seem to occur?

The script seems to touch the printers really quick with the default values, maybe more delay is needed to allow background things to happen.

I havn’t been able to make the problem occur with other drivers. It might be something special with the HP universal driver that throws it off.

I’m really guessing here so far at this point.

I might not have seen this on my production systems because WMI query time is much higher on a system with many printers active. Only redirecting the default printer reduces the time.

Can you play around and see if you can make the problem occur anymore?

Thanks,

Zach

**Comment by awalesa** [comment]
Hi Zach,

THANKS FOR SUPPORT! I will test the settings you wrote and let you know how it goes. One again - THANKS!

Alex

**Comment by awalesa** [comment]
HI

It's much better now! I have tested it serveral times and looks ok. I will test it more deeply to confirm that changing timeouts resolves the problem.

THANKS!

Alex

**Comment by zniezelski** [comment]
Alex,

I think adjusting the time values to give it more of a delay before making changes will greatly reduce the odds of the problem occurring. I think there may still be a chance that the printer could be changed too fast if multiple users login to the server at the same time because the scheduled task adds the task to the queue when a user logs in while the task is already running.

I added these lines on your server starting on line 1592 on printer.ps1
##
$ActiveUsers = (Get-TSSession  | where {$_.State -eq "Active"}).count
if ($ActiveUsers -gt $previoususers) {exit}
$previoususers = $ActiveUsers

##

It should help further reduce the chance of the problem occurring because it will stop the script if it detects a new user logon and let the queued up task take over.

I’m going to keep playing. Let me know how your testing goes. Let me know if anything goofy at all happens.

Thanks,

Zach

**Comment by zniezelski** [comment]
Alex,

Do you feel the problem is resolved? I’ve been logging in once and awhile. I noticed the redirected printer never shows in devices and printers anymore. I’m not sure why. I can’t make the problem occur on my test machine. Sometimes the locally re-created printer doesn’t show in devices and printers.

It seems to always map properly in the print dialog window. Is this a problem? Other non-universal driver printers seem to display without trouble.

In the next release I think I’m going to change some things that will give the redirected printers some more time to finish before changes are applied.

Thanks,

Zach

**Comment by awalesa** [comment]
Hi, it seems that sometimes it is unstable - the printer for example is not set as default printer in rdp session. I'm still trying to catch when it has problems.

**Comment by zniezelski** [comment]
Alex,

Are you still experiencing trouble? I'm working on a new release of Printerceptor. I added more delay to the parts of the script that make changes to printers. 

I haven't been able to make the problem occur in my test setup, would you like to give it a try?
1. go to https://github.com/zniezelski/Printerceptor/blob/master/printer.ps1
2. Right click on "raw" and save to C:\program files\printerceptor\printer.ps1
3. go to C:\program files\printerceptor, right click on "printer,ps1" go to "properties" and click "unblock"
4. Open "Printerceptor", go to "options". make "amount of round passes" 5 and "additional wait time in seconds between rounds" 15
5. Test

Thanks,

Zach

**Comment by awalesa** [comment]
Hi Zach,

We are live from 3 days on new server using version we have prepared last time. It’s about 30 terminal users without problems until now ☺ Of course I will try in couple of days – just let me rest after migration ☺

## 

z pozdrowieniami,

Aleksander Wałęsa

tel. 500 175 009

e-mail: awalesa@itlab.plmailto:awalesa@itlab.pl

---

ITlab.pl sp. z o.o.

ul. Katowicka 60, 41-400 Mysłowice

NIP: 2220900563, REGON: 364132515, KRS: 0000611040

Sąd Rejonowy Katowice-Wschód w Katowicach wydział VIII Gospodarczy KRS

Kapitał zakładowy: 6 000,00 zł

**Comment by zniezelski** [comment]
Alex,

Do you still need assistance with this?

Thanks,

Zach
