### ISSUE TITLE
Renaming works, but printing doesn't - Easy Print Driver Different Name in Server 2008 SP2

### ISSUE THREAD

**Issue by StrikerTwo** [zniezelski/Printerceptor#6]
I'm running an old Windows 2008 Terminal Server with a legacy healthcare application on it. To print the forms the doctor needs, you need to explicitly configure the printer by name. It won't just print on the client default printer.
This of course leads to a problem when the printer is redirected from the client and gets renamed every time. In comes your nice solution.

But: Renaming the printers via Printerceptor works fine, the application picks the new name up, but printing does not work. Even printing a test page from Windows directly gives an error as soon as the printer is renamed.
Stop the Printerceptor task and connect again - everything is fine (but you need to reconfigure the application, of course).

Any ideas?

**Comment by zniezelski** [comment]
StrickerTwo,
The script was created exactly for the problem you are having. Is it running windows server 2008 SP2 or R2? Can you please let me know which driver the printer is using on the terminal server? I’ll see if I can re-create the problem.
Is the server fully windows updated?
Did you happen to try the recreate feature to see if the printer works by re-creation. That might work.
The script will not work with easy print driver.

Thanks,

Zach

**Comment by zniezelski** [comment]
StrickerTwo,

I might have figured out the problem. The easy print driver in server 2008 SP2 is called "Terminal Services Easy Print" and on server 2008 R2 it is called "Remote Desktop Easy Print".

The script excludes the "Remote Desktop Easy Print" driver because its a known problem that an easy print driver printer will not print after renaming. The script doesn't exclude the name the easy print driver is called in SP2. I haven't tested the script in 2008 SP2. 

I think adding the print driver to the server and settings the server to not use easy print driver first in group policy will make it work for you. Check the box to exclude the "Terminal Services Easy Print" driver so it does not rename and break printers.

Let me know if this helps.

Thanks,

Zach

**Comment by StrikerTwo** [comment]
Thanks for your quick reply. You are right, the printer is using the "Terminal Services Easy Print" driver.
I'll try my luck with the Group Policy, have to read up on that first.

**Comment by zniezelski** [comment]
Here is a video of how to install the driver and make easy print not the first choice in server 2012 R2. It should be similar steps: https://www.youtube.com/watch?v=VinNQ94PdNA&feature=youtu.be

**Comment by zniezelski** [comment]
Were you able to get it work?

Thanks,

Zach

**Comment by zniezelski** [comment]
StrikerTwo,

Were you able to get the script to work. Please let me know if you need further assistance.

Thanks,

Zach

**Comment by StrikerTwo** [comment]
Hi,

thanks for asking. My client basically gave up on this issue. They'll switch to networked printers where they can and fill the forms by hand in the few cases where they cannot (they work in a remote office every few months where they can VPN to the terminal server).

Best regards,
Chris
